name: 'h3dev'

services: 
  mydb:
    build: ./mysql
    restart: unless-stopped
    secrets:
      - mysql_root_password
    environment:
      # maps the filepath to the mysql root password secret to the MYSQL_ROOT_PASSWORD environment variable in the container. This allows the mysql server to read the root password from the secret file when it starts up. 
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      # .env file used in the docker compose --env-file command defines the path on the host machine
      - ${MYSQL_DATA_DIR}:/var/lib/mysql # using relative path to bind host dir to persist mysql data
      - ${HEURISTFILE_STORE}:/var/heuristfilestore # using relative path to bind host dir to /var/heuristfilestore
    ports:
      - "3306:3306"

  myadmin:
    build: ./myadmin
    restart: unless-stopped
    environment: 
     PMA_HOST: mydb
     PMA_PASSWORD_: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80" # "host_port:container_port". phpmyadmin can be found from host browser as localhost:8080
    volumes: 
      # .env file used in the docker compose --env-file command defines the path on the host machine
      - ${HEURISTFILE_STORE}:/var/heuristfilestore # using relative path to bind host dir to /var/heuristfilestore
      - ${MYADMIN_DIR}:/var/lib/myadmin # using relative path to bind host dir to /myadmin_queries
      - ${MYADMIN_STORAGE_DIR}:/var/lib/myadmin/storage
#      - ../../../heuristfilestore:/var/heuristfilestore # using relative path to bind host dir to /var/heuristfilestore
#      - ../../../heuristfilestore/myadmin:/var/lib/myadmin # using relative path to bind host dir to /myadmin_queries
#      - ../../../heuristfilestore/myadminstorage:/var/lib/myadmin/storage
    depends_on: 
     - mydb
#      mydb:
#        condition: service_healthy
       
  h3zag:
    build: ./php-apache-dev
    ports:
      - "80:80" # map container port 80 to host port 80. This will allow the use of localhost directly
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - hro_username
      - hro_password
      - hrw_username
      - hrw_password
      - hpwd_4dbcreate
      - mysql_servername
      - heurist_servername
      - hdefault_dbname
    environment:
      HRO_USER_FILE: /run/secrets/hro_username
      HRO_PASS_FILE: /run/secrets/hro_password
      HRW_USER_FILE: /run/secrets/hrw_username
      HRW_PASS_FILE: /run/secrets/hrw_password
      HPWD_4DBCREATE_FILE: /run/secrets/hpwd_4dbcreate
      MYSQL_SERVERNAME_FILE: /run/secrets/mysql_servername
      HEURIST_SERVERNAME_FILE: /run/secrets/heurist_servername
      HDEFAULT_DBNAME_FILE: /run/secrets/hdefault_dbname
    volumes: 
      # .env file used in the docker compose --env-file command defines the path on the host machine
      - ${PATH_TO_HEURIST_SITE}:/var/www/html/ # path_to_workspaceroot:absolute path in apache container for document root
      - ${HEURISTFILE_STORE}:/var/www/html/HEURIST_FILESTORE # path_to_database_sql files:absolute path to apache container of heuristfilestore
      - ${ZAP_WWWDATA_DIR}:/var/www/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
      - ${ZAP_DATA_DIR}:/var/www/html/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
      - ${ZAP_DATA_DIR}:/srv/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
#      - ../..:/var/www/html/ # path_to_workspaceroot:absolute path in apache container for document root
#      - ../../../heuristfilestore:/var/www/html/HEURIST_FILESTORE # path_to_database_sql files:absolute path to apache container of heuristfilestore
#      - ../../../heuristfilestore/ZAPData:/var/www/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
#      - ../../../heuristfilestore/ZAPData:/var/www/html/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
#      - ../../../heuristfilestore/ZAPData:/srv/ZAPData # path_to_database_sql files:absolute path to apache container of heuristfilestore
    depends_on: 
     - mydb
#      mydb:
#        condition: service_healthy

  memcached_server:
    image: memcached:latest
    container_name: machedsrv
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 64 -o modern

secrets:
  # paths below assumes docker directory is sibling to secrets directory. Adjust paths if your directory structure is different.
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  hro_username:
    file: ../secrets/hro_username.txt
  hro_password:
    file: ../secrets/hro_password.txt
  hrw_username:
    file: ../secrets/hrw_username.txt
  hrw_password:
    file: ../secrets/hrw_password.txt
  hpwd_4dbcreate:
    file: ../secrets/hpwd_4dbcreate.txt
  mysql_servername:
    file: ../secrets/mysql_servername.txt
  heurist_servername:
    file: ../secrets/heurist_servername.txt
  hdefault_dbname:
    file: ../secrets/hdefault_dbname.txt

#  redis:
#    image: 'redis:3.0-alpine'
#    command: redis-server --requirepass devpassword
#    volumes:
#      - 'redis:/var/lib/redis/data'
#    ports:
#      - '6379:6379'

#  readmin:
#    build: ../admin
#    command: >
#      gunicorn -b 0.0.0.0:8000
#        --access-logfile -
#        --reload
#        --workers=2
#        "wsgi:application"
#    environment:
#      PYTHONUNBUFFERED: 'true'
#    env_file:
#      - ../.env
#    volumes:
#      - '../admin:/readadmin'
#      - sharebin:/usr/bin # share mysql tools with php server to help maintain databases
#      - ../../../heuristfilestore:/var/www/heuristfilestore # path_to_database_sql's:absolute path to apache container of readfilestore
#    ports:
#      - '8001:8000'

#volumes: #these volumes will be saved in docker storage until deleted
#  sharebin:
#  db-data:
#  db-pgadmin:
#  redis:
